name: Update J-POP Collection

on:
  schedule:
    - cron: '* * * * *' # 每分鐘執行一次
  workflow_dispatch: # 允許手動執行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 升級到 v4 以支援新版 Node.js

      - name: Set up Python
        uses: actions/setup-python@v5 # 升級到 v5 以支援新版 Node.js
        with:
          python-version: '3.x'

      - name: Run Curator Script
        run: python curator.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "Auto-Curator"
          git config --global user.email "bot@github.com"
          git add data.json
          git commit -m "Automated update: 5 new songs" || exit 0
          git push
